name: optopus
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vector_math: ^2.1.4
  flutter_colorpicker: ^1.1.0
  lottie: ^1.4.3
  google_fonts: ^7.1.0
  supabase_flutter: ^2.6.0
  flutter_riverpod: ^3.1.0    
  riverpod_annotation: ^4.0.0 
  go_router: ^17.0.1
  fpdart: ^1.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  windows_single_instance: 1.1.0
  app_links: ^6.4.1
  protocol_handler: ^0.2.0

  flow_canvas:
    path: packages/flow_canvas
  url_launcher: ^6.3.2
  bitsdojo_window: ^0.1.6
  equatable: ^2.0.8
  http: ^1.6.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  freezed: ^3.2.0
  riverpod_generator: ^4.0.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/no_data.jpg
    - assets/blank_workspace_image.png
    - lib/core/env/.env